/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'phone' : IDL.Text,
  'listId' : IDL.Text,
});
export const CampaignStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'draft' : IDL.Null,
  'failed' : IDL.Null,
  'running' : IDL.Null,
  'paused' : IDL.Null,
});
export const Campaign = IDL.Record({
  'id' : IDL.Text,
  'status' : CampaignStatus,
  'failedCount' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalContacts' : IDL.Nat,
  'sentCount' : IDL.Nat,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'progress' : IDL.Nat,
  'message' : IDL.Text,
  'delaySeconds' : IDL.Nat,
  'listId' : IDL.Text,
  'scheduledAt' : IDL.Opt(IDL.Int),
});
export const WaClientStatus = IDL.Variant({
  'disconnected' : IDL.Null,
  'connected' : IDL.Null,
  'connecting' : IDL.Null,
});
export const WaClient = IDL.Record({
  'id' : IDL.Text,
  'status' : WaClientStatus,
  'displayName' : IDL.Text,
  'connectedAt' : IDL.Opt(IDL.Int),
  'phone' : IDL.Opt(IDL.Text),
});
export const ContactList = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'contactCount' : IDL.Nat,
});
export const GroupMember = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactsGrowthStat = IDL.Record({
  'total' : IDL.Nat,
  'date' : IDL.Text,
});
export const DailyMessageStat = IDL.Record({
  'date' : IDL.Text,
  'count' : IDL.Nat,
});
export const CampaignPerformanceStat = IDL.Record({
  'sent' : IDL.Nat,
  'campaignName' : IDL.Text,
  'failed' : IDL.Nat,
});
export const AnalyticsData = IDL.Record({
  'contactsGrowth' : IDL.Vec(ContactsGrowthStat),
  'dailyMessages' : IDL.Vec(DailyMessageStat),
  'campaignPerformance' : IDL.Vec(CampaignPerformanceStat),
});
export const DashboardSummary = IDL.Record({
  'activeCampaigns' : IDL.Nat,
  'totalContacts' : IDL.Nat,
  'connectedClients' : IDL.Nat,
  'messagesToday' : IDL.Nat,
});
export const MessageStatus = IDL.Variant({
  'sent' : IDL.Null,
  'queued' : IDL.Null,
  'failed' : IDL.Null,
});
export const MessageLog = IDL.Record({
  'id' : IDL.Text,
  'status' : MessageStatus,
  'contactName' : IDL.Text,
  'campaignId' : IDL.Text,
  'timestamp' : IDL.Int,
  'contactId' : IDL.Text,
  'errorMsg' : IDL.Opt(IDL.Text),
  'contactPhone' : IDL.Text,
});
export const AppSettings = IDL.Record({
  'activeHoursEnd' : IDL.Text,
  'activeHoursStart' : IDL.Text,
  'nodeBackendUrl' : IDL.Text,
  'dailyLimit' : IDL.Nat,
  'delaySeconds' : IDL.Nat,
  'warmupMode' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Contact], []),
  'cancelCampaign' : IDL.Func([IDL.Text], [Campaign], []),
  'connectClient' : IDL.Func([IDL.Text], [WaClient], []),
  'createCampaign' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Opt(IDL.Int),
      ],
      [Campaign],
      [],
    ),
  'createContactList' : IDL.Func([IDL.Text, IDL.Text], [ContactList], []),
  'deleteCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteContact' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteContactList' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'disconnectClient' : IDL.Func([IDL.Text], [WaClient], []),
  'executeCampaign' : IDL.Func([IDL.Text], [Campaign], []),
  'extractGroupMembers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GroupMember)],
      ['query'],
    ),
  'getAnalyticsData' : IDL.Func([], [AnalyticsData], ['query']),
  'getCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getClientQr' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getClients' : IDL.Func([], [IDL.Vec(WaClient)], ['query']),
  'getContactLists' : IDL.Func([], [IDL.Vec(ContactList)], ['query']),
  'getContacts' : IDL.Func([IDL.Text], [IDL.Vec(Contact)], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getMessageLogCount' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      ['query'],
    ),
  'getMessageLogs' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
      [IDL.Vec(MessageLog)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [AppSettings], ['query']),
  'importContacts' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text })),
      ],
      [IDL.Nat],
      [],
    ),
  'pauseCampaign' : IDL.Func([IDL.Text], [Campaign], []),
  'tickCampaignProgress' : IDL.Func([IDL.Text], [Campaign], []),
  'updateSettings' : IDL.Func([AppSettings], [AppSettings], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'phone' : IDL.Text,
    'listId' : IDL.Text,
  });
  const CampaignStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'draft' : IDL.Null,
    'failed' : IDL.Null,
    'running' : IDL.Null,
    'paused' : IDL.Null,
  });
  const Campaign = IDL.Record({
    'id' : IDL.Text,
    'status' : CampaignStatus,
    'failedCount' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalContacts' : IDL.Nat,
    'sentCount' : IDL.Nat,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'progress' : IDL.Nat,
    'message' : IDL.Text,
    'delaySeconds' : IDL.Nat,
    'listId' : IDL.Text,
    'scheduledAt' : IDL.Opt(IDL.Int),
  });
  const WaClientStatus = IDL.Variant({
    'disconnected' : IDL.Null,
    'connected' : IDL.Null,
    'connecting' : IDL.Null,
  });
  const WaClient = IDL.Record({
    'id' : IDL.Text,
    'status' : WaClientStatus,
    'displayName' : IDL.Text,
    'connectedAt' : IDL.Opt(IDL.Int),
    'phone' : IDL.Opt(IDL.Text),
  });
  const ContactList = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'contactCount' : IDL.Nat,
  });
  const GroupMember = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const ContactsGrowthStat = IDL.Record({
    'total' : IDL.Nat,
    'date' : IDL.Text,
  });
  const DailyMessageStat = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
  const CampaignPerformanceStat = IDL.Record({
    'sent' : IDL.Nat,
    'campaignName' : IDL.Text,
    'failed' : IDL.Nat,
  });
  const AnalyticsData = IDL.Record({
    'contactsGrowth' : IDL.Vec(ContactsGrowthStat),
    'dailyMessages' : IDL.Vec(DailyMessageStat),
    'campaignPerformance' : IDL.Vec(CampaignPerformanceStat),
  });
  const DashboardSummary = IDL.Record({
    'activeCampaigns' : IDL.Nat,
    'totalContacts' : IDL.Nat,
    'connectedClients' : IDL.Nat,
    'messagesToday' : IDL.Nat,
  });
  const MessageStatus = IDL.Variant({
    'sent' : IDL.Null,
    'queued' : IDL.Null,
    'failed' : IDL.Null,
  });
  const MessageLog = IDL.Record({
    'id' : IDL.Text,
    'status' : MessageStatus,
    'contactName' : IDL.Text,
    'campaignId' : IDL.Text,
    'timestamp' : IDL.Int,
    'contactId' : IDL.Text,
    'errorMsg' : IDL.Opt(IDL.Text),
    'contactPhone' : IDL.Text,
  });
  const AppSettings = IDL.Record({
    'activeHoursEnd' : IDL.Text,
    'activeHoursStart' : IDL.Text,
    'nodeBackendUrl' : IDL.Text,
    'dailyLimit' : IDL.Nat,
    'delaySeconds' : IDL.Nat,
    'warmupMode' : IDL.Bool,
  });
  
  return IDL.Service({
    'addContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Contact], []),
    'cancelCampaign' : IDL.Func([IDL.Text], [Campaign], []),
    'connectClient' : IDL.Func([IDL.Text], [WaClient], []),
    'createCampaign' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Opt(IDL.Int),
        ],
        [Campaign],
        [],
      ),
    'createContactList' : IDL.Func([IDL.Text, IDL.Text], [ContactList], []),
    'deleteCampaign' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteContact' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteContactList' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'disconnectClient' : IDL.Func([IDL.Text], [WaClient], []),
    'executeCampaign' : IDL.Func([IDL.Text], [Campaign], []),
    'extractGroupMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GroupMember)],
        ['query'],
      ),
    'getAnalyticsData' : IDL.Func([], [AnalyticsData], ['query']),
    'getCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getClientQr' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getClients' : IDL.Func([], [IDL.Vec(WaClient)], ['query']),
    'getContactLists' : IDL.Func([], [IDL.Vec(ContactList)], ['query']),
    'getContacts' : IDL.Func([IDL.Text], [IDL.Vec(Contact)], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getMessageLogCount' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        ['query'],
      ),
    'getMessageLogs' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
        [IDL.Vec(MessageLog)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [AppSettings], ['query']),
    'importContacts' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text })),
        ],
        [IDL.Nat],
        [],
      ),
    'pauseCampaign' : IDL.Func([IDL.Text], [Campaign], []),
    'tickCampaignProgress' : IDL.Func([IDL.Text], [Campaign], []),
    'updateSettings' : IDL.Func([AppSettings], [AppSettings], []),
  });
};

export const init = ({ IDL }) => { return []; };