/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsData {
  'contactsGrowth' : Array<ContactsGrowthStat>,
  'dailyMessages' : Array<DailyMessageStat>,
  'campaignPerformance' : Array<CampaignPerformanceStat>,
}
export interface AppSettings {
  'activeHoursEnd' : string,
  'activeHoursStart' : string,
  'nodeBackendUrl' : string,
  'dailyLimit' : bigint,
  'delaySeconds' : bigint,
  'warmupMode' : boolean,
}
export interface Campaign {
  'id' : string,
  'status' : CampaignStatus,
  'failedCount' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'totalContacts' : bigint,
  'sentCount' : bigint,
  'mediaUrl' : [] | [string],
  'progress' : bigint,
  'message' : string,
  'delaySeconds' : bigint,
  'listId' : string,
  'scheduledAt' : [] | [bigint],
}
export interface CampaignPerformanceStat {
  'sent' : bigint,
  'campaignName' : string,
  'failed' : bigint,
}
export type CampaignStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'draft' : null } |
  { 'failed' : null } |
  { 'running' : null } |
  { 'paused' : null };
export interface Contact {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'phone' : string,
  'listId' : string,
}
export interface ContactList {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'contactCount' : bigint,
}
export interface ContactsGrowthStat { 'total' : bigint, 'date' : string }
export interface DailyMessageStat { 'date' : string, 'count' : bigint }
export interface DashboardSummary {
  'activeCampaigns' : bigint,
  'totalContacts' : bigint,
  'connectedClients' : bigint,
  'messagesToday' : bigint,
}
export interface GroupMember { 'name' : string, 'phone' : string }
export interface MessageLog {
  'id' : string,
  'status' : MessageStatus,
  'contactName' : string,
  'campaignId' : string,
  'timestamp' : bigint,
  'contactId' : string,
  'errorMsg' : [] | [string],
  'contactPhone' : string,
}
export type MessageStatus = { 'sent' : null } |
  { 'queued' : null } |
  { 'failed' : null };
export interface WaClient {
  'id' : string,
  'status' : WaClientStatus,
  'displayName' : string,
  'connectedAt' : [] | [bigint],
  'phone' : [] | [string],
}
export type WaClientStatus = { 'disconnected' : null } |
  { 'connected' : null } |
  { 'connecting' : null };
export interface _SERVICE {
  'addContact' : ActorMethod<[string, string, string], Contact>,
  'cancelCampaign' : ActorMethod<[string], Campaign>,
  'connectClient' : ActorMethod<[string], WaClient>,
  'createCampaign' : ActorMethod<
    [string, string, string, [] | [string], bigint, [] | [bigint]],
    Campaign
  >,
  'createContactList' : ActorMethod<[string, string], ContactList>,
  'deleteCampaign' : ActorMethod<[string], boolean>,
  'deleteContact' : ActorMethod<[string], boolean>,
  'deleteContactList' : ActorMethod<[string], boolean>,
  'disconnectClient' : ActorMethod<[string], WaClient>,
  'executeCampaign' : ActorMethod<[string], Campaign>,
  'extractGroupMembers' : ActorMethod<[string], Array<GroupMember>>,
  'getAnalyticsData' : ActorMethod<[], AnalyticsData>,
  'getCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getClientQr' : ActorMethod<[string], [] | [string]>,
  'getClients' : ActorMethod<[], Array<WaClient>>,
  'getContactLists' : ActorMethod<[], Array<ContactList>>,
  'getContacts' : ActorMethod<[string], Array<Contact>>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getMessageLogCount' : ActorMethod<[[] | [string], [] | [string]], bigint>,
  'getMessageLogs' : ActorMethod<
    [[] | [string], [] | [string], bigint, bigint],
    Array<MessageLog>
  >,
  'getSettings' : ActorMethod<[], AppSettings>,
  'importContacts' : ActorMethod<
    [string, Array<{ 'name' : string, 'phone' : string }>],
    bigint
  >,
  'pauseCampaign' : ActorMethod<[string], Campaign>,
  'tickCampaignProgress' : ActorMethod<[string], Campaign>,
  'updateSettings' : ActorMethod<[AppSettings], AppSettings>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];