/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GroupMember {
    name: string;
    phone: string;
}
export interface Contact {
    id: string;
    name: string;
    createdAt: bigint;
    phone: string;
    listId: string;
}
export interface MessageLog {
    id: string;
    status: MessageStatus;
    contactName: string;
    campaignId: string;
    timestamp: bigint;
    contactId: string;
    errorMsg?: string;
    contactPhone: string;
}
export interface DashboardSummary {
    activeCampaigns: bigint;
    totalContacts: bigint;
    connectedClients: bigint;
    messagesToday: bigint;
}
export interface AppSettings {
    activeHoursEnd: string;
    activeHoursStart: string;
    nodeBackendUrl: string;
    dailyLimit: bigint;
    delaySeconds: bigint;
    warmupMode: boolean;
}
export interface ContactsGrowthStat {
    total: bigint;
    date: string;
}
export interface ContactList {
    id: string;
    name: string;
    createdAt: bigint;
    description: string;
    contactCount: bigint;
}
export interface CampaignPerformanceStat {
    sent: bigint;
    campaignName: string;
    failed: bigint;
}
export interface WaClient {
    id: string;
    status: WaClientStatus;
    displayName: string;
    connectedAt?: bigint;
    phone?: string;
}
export interface Campaign {
    id: string;
    status: CampaignStatus;
    failedCount: bigint;
    name: string;
    createdAt: bigint;
    totalContacts: bigint;
    sentCount: bigint;
    mediaUrl?: string;
    progress: bigint;
    message: string;
    delaySeconds: bigint;
    listId: string;
    scheduledAt?: bigint;
}
export interface DailyMessageStat {
    date: string;
    count: bigint;
}
export interface AnalyticsData {
    contactsGrowth: Array<ContactsGrowthStat>;
    dailyMessages: Array<DailyMessageStat>;
    campaignPerformance: Array<CampaignPerformanceStat>;
}
export enum CampaignStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed",
    draft = "draft",
    failed = "failed",
    running = "running",
    paused = "paused"
}
export enum MessageStatus {
    sent = "sent",
    queued = "queued",
    failed = "failed"
}
export enum WaClientStatus {
    disconnected = "disconnected",
    connected = "connected",
    connecting = "connecting"
}
export interface backendInterface {
    addContact(listId: string, name: string, phone: string): Promise<Contact>;
    cancelCampaign(id: string): Promise<Campaign>;
    connectClient(clientId: string): Promise<WaClient>;
    createCampaign(name: string, listId: string, message: string, mediaUrl: string | null, delaySeconds: bigint, scheduledAt: bigint | null): Promise<Campaign>;
    createContactList(name: string, description: string): Promise<ContactList>;
    deleteCampaign(id: string): Promise<boolean>;
    deleteContact(id: string): Promise<boolean>;
    deleteContactList(id: string): Promise<boolean>;
    disconnectClient(clientId: string): Promise<WaClient>;
    executeCampaign(id: string): Promise<Campaign>;
    extractGroupMembers(groupId: string): Promise<Array<GroupMember>>;
    getAnalyticsData(): Promise<AnalyticsData>;
    getCampaigns(): Promise<Array<Campaign>>;
    getClientQr(clientId: string): Promise<string | null>;
    getClients(): Promise<Array<WaClient>>;
    getContactLists(): Promise<Array<ContactList>>;
    getContacts(listId: string): Promise<Array<Contact>>;
    getDashboardSummary(): Promise<DashboardSummary>;
    getMessageLogCount(campaignId: string | null, status: string | null): Promise<bigint>;
    getMessageLogs(campaignId: string | null, status: string | null, limit: bigint, offset: bigint): Promise<Array<MessageLog>>;
    getSettings(): Promise<AppSettings>;
    importContacts(listId: string, items: Array<{
        name: string;
        phone: string;
    }>): Promise<bigint>;
    pauseCampaign(id: string): Promise<Campaign>;
    tickCampaignProgress(id: string): Promise<Campaign>;
    updateSettings(settings: AppSettings): Promise<AppSettings>;
}
import type { Campaign as _Campaign, CampaignStatus as _CampaignStatus, MessageLog as _MessageLog, MessageStatus as _MessageStatus, WaClient as _WaClient, WaClientStatus as _WaClientStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addContact(arg0: string, arg1: string, arg2: string): Promise<Contact> {
        if (this.processError) {
            try {
                const result = await this.actor.addContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContact(arg0, arg1, arg2);
            return result;
        }
    }
    async cancelCampaign(arg0: string): Promise<Campaign> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelCampaign(arg0);
                return from_candid_Campaign_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelCampaign(arg0);
            return from_candid_Campaign_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async connectClient(arg0: string): Promise<WaClient> {
        if (this.processError) {
            try {
                const result = await this.actor.connectClient(arg0);
                return from_candid_WaClient_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectClient(arg0);
            return from_candid_WaClient_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCampaign(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: bigint, arg5: bigint | null): Promise<Campaign> {
        if (this.processError) {
            try {
                const result = await this.actor.createCampaign(arg0, arg1, arg2, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Campaign_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCampaign(arg0, arg1, arg2, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Campaign_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createContactList(arg0: string, arg1: string): Promise<ContactList> {
        if (this.processError) {
            try {
                const result = await this.actor.createContactList(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContactList(arg0, arg1);
            return result;
        }
    }
    async deleteCampaign(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCampaign(arg0);
            return result;
        }
    }
    async deleteContact(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async deleteContactList(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactList(arg0);
            return result;
        }
    }
    async disconnectClient(arg0: string): Promise<WaClient> {
        if (this.processError) {
            try {
                const result = await this.actor.disconnectClient(arg0);
                return from_candid_WaClient_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disconnectClient(arg0);
            return from_candid_WaClient_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async executeCampaign(arg0: string): Promise<Campaign> {
        if (this.processError) {
            try {
                const result = await this.actor.executeCampaign(arg0);
                return from_candid_Campaign_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.executeCampaign(arg0);
            return from_candid_Campaign_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async extractGroupMembers(arg0: string): Promise<Array<GroupMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.extractGroupMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.extractGroupMembers(arg0);
            return result;
        }
    }
    async getAnalyticsData(): Promise<AnalyticsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsData();
            return result;
        }
    }
    async getCampaigns(): Promise<Array<Campaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaigns();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaigns();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientQr(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientQr(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientQr(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClients(): Promise<Array<WaClient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClients();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClients();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactLists(): Promise<Array<ContactList>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactLists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactLists();
            return result;
        }
    }
    async getContacts(arg0: string): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContacts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContacts(arg0);
            return result;
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return result;
        }
    }
    async getMessageLogCount(arg0: string | null, arg1: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageLogCount(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageLogCount(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getMessageLogs(arg0: string | null, arg1: string | null, arg2: bigint, arg3: bigint): Promise<Array<MessageLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageLogs(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageLogs(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async importContacts(arg0: string, arg1: Array<{
        name: string;
        phone: string;
    }>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.importContacts(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importContacts(arg0, arg1);
            return result;
        }
    }
    async pauseCampaign(arg0: string): Promise<Campaign> {
        if (this.processError) {
            try {
                const result = await this.actor.pauseCampaign(arg0);
                return from_candid_Campaign_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pauseCampaign(arg0);
            return from_candid_Campaign_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async tickCampaignProgress(arg0: string): Promise<Campaign> {
        if (this.processError) {
            try {
                const result = await this.actor.tickCampaignProgress(arg0);
                return from_candid_Campaign_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.tickCampaignProgress(arg0);
            return from_candid_Campaign_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: AppSettings): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
}
function from_candid_CampaignStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CampaignStatus): CampaignStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Campaign_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Campaign): Campaign {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_MessageLog_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageLog): MessageLog {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MessageStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageStatus): MessageStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_WaClientStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WaClientStatus): WaClientStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_WaClient_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WaClient): WaClient {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _MessageStatus;
    contactName: string;
    campaignId: string;
    timestamp: bigint;
    contactId: string;
    errorMsg: [] | [string];
    contactPhone: string;
}): {
    id: string;
    status: MessageStatus;
    contactName: string;
    campaignId: string;
    timestamp: bigint;
    contactId: string;
    errorMsg?: string;
    contactPhone: string;
} {
    return {
        id: value.id,
        status: from_candid_MessageStatus_n18(_uploadFile, _downloadFile, value.status),
        contactName: value.contactName,
        campaignId: value.campaignId,
        timestamp: value.timestamp,
        contactId: value.contactId,
        errorMsg: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.errorMsg)),
        contactPhone: value.contactPhone
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _CampaignStatus;
    failedCount: bigint;
    name: string;
    createdAt: bigint;
    totalContacts: bigint;
    sentCount: bigint;
    mediaUrl: [] | [string];
    progress: bigint;
    message: string;
    delaySeconds: bigint;
    listId: string;
    scheduledAt: [] | [bigint];
}): {
    id: string;
    status: CampaignStatus;
    failedCount: bigint;
    name: string;
    createdAt: bigint;
    totalContacts: bigint;
    sentCount: bigint;
    mediaUrl?: string;
    progress: bigint;
    message: string;
    delaySeconds: bigint;
    listId: string;
    scheduledAt?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_CampaignStatus_n3(_uploadFile, _downloadFile, value.status),
        failedCount: value.failedCount,
        name: value.name,
        createdAt: value.createdAt,
        totalContacts: value.totalContacts,
        sentCount: value.sentCount,
        mediaUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.mediaUrl)),
        progress: value.progress,
        message: value.message,
        delaySeconds: value.delaySeconds,
        listId: value.listId,
        scheduledAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.scheduledAt))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _WaClientStatus;
    displayName: string;
    connectedAt: [] | [bigint];
    phone: [] | [string];
}): {
    id: string;
    status: WaClientStatus;
    displayName: string;
    connectedAt?: bigint;
    phone?: string;
} {
    return {
        id: value.id,
        status: from_candid_WaClientStatus_n9(_uploadFile, _downloadFile, value.status),
        displayName: value.displayName,
        connectedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.connectedAt)),
        phone: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    disconnected: null;
} | {
    connected: null;
} | {
    connecting: null;
}): WaClientStatus {
    return "disconnected" in value ? WaClientStatus.disconnected : "connected" in value ? WaClientStatus.connected : "connecting" in value ? WaClientStatus.connecting : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sent: null;
} | {
    queued: null;
} | {
    failed: null;
}): MessageStatus {
    return "sent" in value ? MessageStatus.sent : "queued" in value ? MessageStatus.queued : "failed" in value ? MessageStatus.failed : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    draft: null;
} | {
    failed: null;
} | {
    running: null;
} | {
    paused: null;
}): CampaignStatus {
    return "scheduled" in value ? CampaignStatus.scheduled : "cancelled" in value ? CampaignStatus.cancelled : "completed" in value ? CampaignStatus.completed : "draft" in value ? CampaignStatus.draft : "failed" in value ? CampaignStatus.failed : "running" in value ? CampaignStatus.running : "paused" in value ? CampaignStatus.paused : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Campaign>): Array<Campaign> {
    return value.map((x)=>from_candid_Campaign_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WaClient>): Array<WaClient> {
    return value.map((x)=>from_candid_WaClient_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MessageLog>): Array<MessageLog> {
    return value.map((x)=>from_candid_MessageLog_n16(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
